-- 1. PROFILES TABLE (Extends Supabase Auth users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  -- Public numeric account ID (Binance-style)
  user_uid BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 8746484) UNIQUE,
  email TEXT UNIQUE NOT NULL,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Handle creating profile on new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username)
  VALUES (new.id, new.email, split_part(new.email, '@', 1));
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. WALLETS (Internal Ledger)
-- Everyone has specific asset wallets e.g., 'USDT', 'BTC', 'UGX', 'KES'
CREATE TABLE wallets (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  currency TEXT NOT NULL, -- e.g., 'USDT', 'BTC'
  balance NUMERIC DEFAULT 0.0 CHECK (balance >= 0.0),
  locked_balance NUMERIC DEFAULT 0.0 CHECK (locked_balance >= 0.0), -- Funds in escrow
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, currency)
);

-- Create default USDT wallets on signup
CREATE OR REPLACE FUNCTION public.handle_new_wallet()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.wallets (user_id, currency, balance) VALUES (new.id, 'USDT', 0);
  INSERT INTO public.wallets (user_id, currency, balance) VALUES (new.id, 'BTC', 0);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_profile_created
  AFTER INSERT ON profiles
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_wallet();


-- 3. TRANSACTIONS (Ledger History)
CREATE TABLE transactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  wallet_id UUID REFERENCES wallets(id),
  type TEXT NOT NULL, -- 'deposit', 'withdrawal', 'trade_buy', 'trade_sell', 'transfer', 'transfer_in', 'transfer_out', 'convert_debit', 'convert_credit'
  amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'completed', -- 'pending', 'completed', 'failed'
  reference TEXT UNIQUE, -- tx hash or internal reference
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 4b. WALLET TRANSFERS (CoinCash user to user)
CREATE OR REPLACE FUNCTION public.transfer_wallet_to_user(
  p_source_wallet_id UUID,
  p_recipient_user_id UUID,
  p_amount NUMERIC
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sender_id UUID := auth.uid();
  v_source_wallet_id UUID;
  v_source_wallet_currency TEXT;
  v_source_wallet_balance NUMERIC;
  v_recipient_wallet_id UUID;
  v_recipient_wallet_balance NUMERIC;
  v_amount NUMERIC := round(p_amount::NUMERIC, 8);
  v_reference TEXT := 'TRF-' || to_char(clock_timestamp(), 'YYYYMMDDHH24MISSMS') || '-' || replace(gen_random_uuid()::text, '-', '');
BEGIN
  IF v_sender_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Not authenticated');
  END IF;

  IF v_amount IS NULL OR v_amount <= 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'Enter a valid transfer amount');
  END IF;

  SELECT id, currency, balance
  INTO v_source_wallet_id, v_source_wallet_currency, v_source_wallet_balance
  FROM wallets
  WHERE id = p_source_wallet_id
    AND user_id = v_sender_id
  FOR UPDATE;

  IF NOT FOUND OR v_source_wallet_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Source wallet not found');
  END IF;

  IF p_recipient_user_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Recipient not found');
  END IF;

  IF p_recipient_user_id = v_sender_id THEN
    RETURN jsonb_build_object('success', false, 'error', 'You cannot transfer to your own account');
  END IF;

  SELECT id, balance
  INTO v_recipient_wallet_id, v_recipient_wallet_balance
  FROM wallets
  WHERE user_id = p_recipient_user_id
    AND currency = v_source_wallet_currency
  FOR UPDATE;

  IF NOT FOUND OR v_recipient_wallet_id IS NULL THEN
    INSERT INTO wallets (user_id, currency, balance, locked_balance)
    VALUES (p_recipient_user_id, v_source_wallet_currency, 0, 0)
    RETURNING id, balance INTO v_recipient_wallet_id, v_recipient_wallet_balance;
  END IF;

  IF v_source_wallet_balance < v_amount THEN
    RETURN jsonb_build_object('success', false, 'error', 'Insufficient available balance');
  END IF;

  UPDATE wallets
  SET balance = balance - v_amount
  WHERE id = v_source_wallet_id;

  UPDATE wallets
  SET balance = balance + v_amount
  WHERE id = v_recipient_wallet_id;

  INSERT INTO transactions (wallet_id, type, amount, status, reference)
  VALUES
    (v_source_wallet_id, 'transfer_out', v_amount, 'completed', v_reference || '-OUT'),
    (v_recipient_wallet_id, 'transfer_in', v_amount, 'completed', v_reference || '-IN');

  RETURN jsonb_build_object(
    'success', true,
    'reference', v_reference,
    'currency', v_source_wallet_currency,
    'amount', v_amount,
    'sender_wallet_id', v_source_wallet_id,
    'recipient_wallet_id', v_recipient_wallet_id
  );
EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;


-- 4. P2P ORDERS (The Market Ads)
CREATE TABLE p2p_orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('buy', 'sell')),
  asset TEXT NOT NULL, -- 'USDT', 'BTC'
  fiat TEXT NOT NULL,  -- 'UGX', 'KES', 'USD'
  price NUMERIC NOT NULL,
  total_amount NUMERIC NOT NULL,
  min_limit NUMERIC NOT NULL,
  max_limit NUMERIC NOT NULL,
  payment_method TEXT NOT NULL,
  terms TEXT,
  status TEXT DEFAULT 'active', -- 'active', 'completed', 'cancelled'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 5. P2P TRADES (When an order is taken)
CREATE TABLE p2p_trades (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id UUID REFERENCES p2p_orders(id),
  buyer_id UUID REFERENCES profiles(id),
  seller_id UUID REFERENCES profiles(id),
  asset_amount NUMERIC NOT NULL,
  fiat_amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'pending', -- 'pending', 'paid', 'released', 'disputed', 'cancelled'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 6. MESSAGES (Real-time P2P Chat)
CREATE TABLE messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  trade_id UUID REFERENCES p2p_trades(id) ON DELETE CASCADE,
  sender_id UUID REFERENCES profiles(id),
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Row Level Security) and Realtime for chat
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can insert messages in their trades" ON messages FOR INSERT WITH CHECK (auth.uid() = sender_id);
CREATE POLICY "Users can read trade messages" ON messages FOR SELECT USING (
  trade_id IN (
    SELECT id FROM p2p_trades WHERE buyer_id = auth.uid() OR seller_id = auth.uid()
  )
);

-- Add realtime extension publication
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table messages;

-- 7. SUPPORT MESSAGES (Shared support inbox)
CREATE TABLE support_messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  sender_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  sender_role TEXT NOT NULL CHECK (sender_role IN ('user', 'support')),
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX support_messages_user_id_created_at_idx
  ON support_messages(user_id, created_at DESC);

ALTER TABLE support_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read their support conversation"
ON support_messages FOR SELECT
USING (auth.uid() = user_id OR auth.uid() = sender_id);

CREATE POLICY "Users can send support messages"
ON support_messages FOR INSERT
WITH CHECK (
  auth.uid() = sender_id
  AND auth.uid() = user_id
  AND sender_role = 'user'
);

alter publication supabase_realtime add table support_messages;
