import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0f1014",
        surface: "#0f1014",
        "surface-dim": "#0f1014",
        "surface-bright": "#2a2c32",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#14161d",
        "surface-container": "#1a1d25",
        "surface-container-high": "#21252e",
        "surface-container-highest": "#292d36",
        "surface-variant": "#292d36",
        outline: "#7f8289",
        "outline-variant": "#4a4f59",
        primary: "#f0b90b",
        "primary-dim": "#d6a000",
        "primary-fixed": "#f0b90b",
        "primary-fixed-dim": "#d6a000",
        "primary-container": "#705300",
        secondary: "#f5f6f8",
        "secondary-dim": "#dde0e5",
        "secondary-fixed": "#f5f6f8",
        "secondary-fixed-dim": "#dde0e5",
        "secondary-container": "#3d4250",
        tertiary: "#9ecbff",
        "tertiary-dim": "#6ca9f7",
        "tertiary-fixed": "#9ecbff",
        "tertiary-fixed-dim": "#6ca9f7",
        "tertiary-container": "#1f4575",
        error: "#ff7351",
        "error-dim": "#d53d18",
        "error-container": "#b92902",
        "on-background": "#f3f4f6",
        "on-surface": "#f3f4f6",
        "on-surface-variant": "#b2b6be",
        "on-primary": "#161200",
        "on-primary-container": "#fff7db",
        "on-primary-fixed": "#161200",
        "on-primary-fixed-variant": "#4d3900",
        "on-secondary": "#161922",
        "on-secondary-container": "#f5f6f8",
        "on-secondary-fixed": "#161922",
        "on-secondary-fixed-variant": "#313644",
        "on-tertiary": "#0c223b",
        "on-tertiary-container": "#deecff",
        "on-tertiary-fixed": "#0c223b",
        "on-tertiary-fixed-variant": "#295a90",
        "on-error": "#450900",
        "on-error-container": "#ffd2c8",
        "inverse-primary": "#c89500",
        "inverse-surface": "#f3f4f6",
        "inverse-on-surface": "#4b4f58",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
