import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0b0e11",
        surface: "#0b0e11",
        "surface-dim": "#0b0e11",
        "surface-bright": "#282d31",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#101417",
        "surface-container": "#161a1e",
        "surface-container-high": "#1c2024",
        "surface-container-highest": "#22262b",
        "surface-variant": "#22262b",
        outline: "#737679",
        "outline-variant": "#45484c",
        primary: "#5cfd80",
        "primary-dim": "#4bee74",
        "primary-fixed": "#5cfd80",
        "primary-fixed-dim": "#4bee74",
        "primary-container": "#02c953",
        secondary: "#78f5ae",
        "secondary-dim": "#69e6a1",
        "secondary-fixed": "#78f5ae",
        "secondary-fixed-dim": "#69e6a1",
        "secondary-container": "#006d41",
        tertiary: "#84ecff",
        "tertiary-dim": "#00d4ed",
        "tertiary-fixed": "#00e3fe",
        "tertiary-fixed-dim": "#00d4ed",
        "tertiary-container": "#00e3fe",
        error: "#ff7351",
        "error-dim": "#d53d18",
        "error-container": "#b92902",
        "on-background": "#f8f9fe",
        "on-surface": "#f8f9fe",
        "on-surface-variant": "#a9abaf",
        "on-primary": "#005d22",
        "on-primary-container": "#003711",
        "on-primary-fixed": "#004819",
        "on-primary-fixed-variant": "#006827",
        "on-secondary": "#005a35",
        "on-secondary-container": "#e2ffe8",
        "on-secondary-fixed": "#004528",
        "on-secondary-fixed-variant": "#00653c",
        "on-tertiary": "#005762",
        "on-tertiary-container": "#004d57",
        "on-tertiary-fixed": "#003840",
        "on-tertiary-fixed-variant": "#005762",
        "on-error": "#450900",
        "on-error-container": "#ffd2c8",
        "inverse-primary": "#006e2a",
        "inverse-surface": "#f8f9fe",
        "inverse-on-surface": "#535559",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
